spring:
  datasource:
      url: jdbc:mysql://localhost:3306/pjm?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
      username: root
      password: root
mybatis:
   mapperLocations: classpath:/mapper/*.xml
